language: node_js
node_js:
- node
cache:
  directories:
  - $(npm config get prefix)/lib/node_modules
before_script:
- npm install -g ganache-cli truffle solium
- ganache-cli -p 8545 > /dev/null &
- sleep 5
script:
- solium -d contracts
- truffle compile
- truffle test
