language: node_js
node_js:
- node
cache:
  directories:
  - $(npm config get prefix)/lib/node_modules
before_script:
- npm install -g ganache-cli truffle solium
- ganache-cli -p 8545 > /dev/null &
- npm install
script:
- solium -d contracts
- truffle compile
- truffle test
- ./node_modules/.bin/solidity-coverage
- bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
