language: node_js
node_js:
- node
cache:
  directories:
  - $(npm config get prefix)/lib/node_modules
before_script:
- npm install -g ganache-cli truffle
- ganache-cli -p 7545 > /dev/null &
- sleep 5
script:
- truffle compile
- truffle test
