language: node_js
node_js:
- node
cache:
  directories:
  - "$(npm config get prefix)/lib/node_modules"
  - "$(npm config get prefix)/web/node_modules"
before_script:
# - npm install -g truffle solium
- npm install -g solium
- npm install
script:
- solium -d contracts
# - truffle test

# Temporary Solution - It seems that Travis always compiles using the solc v5
# even when it should use solc v4 as specified in truffle.js config.
# - "./node_modules/.bin/solidity-coverage"
# - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

# - truffle compile
# - cp -r ./build/contracts ./web/src/contracts
- npm install --prefix web
- npm run-script --prefix web build
deploy:
  provider: s3
  access_key_id: "$S3_access_key_id"
  secret_access_key: "$S3_secret_access_key"
  bucket: ens.topmonks.com
  acl: public_read
  local_dir: web/build
  skip_cleanup: true
  region: eu-central-1
