language: node_js
node_js:
- node
cache:
  directories:
  - "$(npm config get prefix)/lib/node_modules"
  - "$(npm config get prefix)/web/node_modules"
before_script:
- npm install -g truffle solium
- npm install
script:
- solium -d contracts
- truffle test
- "./node_modules/.bin/solidity-coverage"
- bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
- truffle compile
- cp ./build/contracts ./web/src/contracts
- npm install --prefix web
- npm run-script --prefix web build
deploy:
  provider: s3
  access_key_id: AKIAIYMKIXJGGEZTJWHQ
  secret_access_key:
    secure: TaxbQx5Oq8cjJK66paubt6/tAmn1fkhcgjXoJfGTzBHvRRBf4DBrcf+gSkDCexqrGCAD2Gkc/rs1O4uzes0JIuEhXLCHHCBMleFx1btpIJd4cpISRXaN4dY8Fbo54sEk9SbsSa5EnzEW8Z2htPYacMaR+eR052S6AGWWGtVIF26QX+SJPy6yRxE3/UtC7QClVUYq4Ul8PYL1Cklp5PRzx9oV890ikVTIYAPEhmVe+XCrSgqcp90TIZ1Op2GTQeviRV/o8l1tsWTSD91QMvc0UUEQDyur8v05qg+fVLxn1HaVzjC2PjDp45ZjCgNUgzsc/QbgK7BMPmQhHUHJv1u2H6GmQncbdr7p0/bpvTwYwiowsMMXZ8aU4E9aE97wQxKrgYxOA6uaNw1x8Ss4d+9SmaoUOOiXEEqqs06vGO33rR5942Fx4zu2VKxtcU8FFppcKHGLQh2PolpGerw9YuN8sNjalabjBhuBCyfUZuQtD+doKRbxxC0nxvJWkDXtv32dbwLUMhL5o6ESwNVVzA+Nw1ss2G3YZdNOik4mWmw+fgH1sHWBaRscvKSpy1LEwZAh8Gd8Cu38ICZGWIFuZP31ED5VqHTWBLmOpzzfWlgCxanWWVRLw0183WOhOI+zxNAaxrIlgxl3XjEcomEa/CML7aRr5UAldNxtYZrlKCZA5LM=
  bucket: ens.topmonks.com
  acl: public_read
  local_dir: web/build
  skip_cleanup: true
  region: eu-central-1
